@startuml
hide circle
' <|-- is "extention" and used for class inheritence
' *-- is composition (static aggregation), for when b is permanently "part of" a
' o-- is aggregation (dynamic aggregation)

class Map {
    -Hex[] hexes
	Hex getHex(int)
}

class Hex {
	-Hex[] neighbors
    -number
    -province
    -terrain
    -terrainImprovement
    +getNumber()
    +getProvince()
    +getMovementCost(Hex enterHex, Race)
    +getCombatEffect()
    +getTerrain()
    +getTerrainImprovement()
	+getHexEdge(Direction)
    +getNeighbor(Direction)
}

Map *-- "2046" Hex
Hex *-- "6" HexEdge
Hex *-- TerrainImprovementType
Hex *-- TerrainType
Hex *-- "0..1" Capitol
Hex o-- "0..n" UnitStack
Hex o-- "0..1" Vortex
HexEdge *-- "0..1" Border
HexEdge *-- "0..1" Stream
HexEdge *-- "0..1" Wall
                   Wall <|-- SolidWall
                   Wall <|-- Gate
HexEdge o-- "0..1" ForceWall
TerrainType <|-- Broken
TerrainType <|-- Clear
TerrainType <|-- Cultivated
TerrainType <|-- Forest
TerrainType <|-- Glacier
TerrainType <|-- Karoo
TerrainType <|-- Moat
TerrainType <|-- River
TerrainType <|-- Lake
TerrainType <|-- Mountain
TerrainType <|-- Rough
TerrainType <|-- Swamp
TerrainType <|-- Woods
TerrainType <|-- VortexTerrain
TerrainType <|-- Blasted
TerrainImprovementType <|-- Bridge
TerrainImprovementType <|-- Castle
TerrainImprovementType <|-- City
TerrainImprovementType <|-- DragonTunnel
TerrainImprovementType <|-- Ford
TerrainImprovementType <|-- Portal
TerrainImprovementType <|-- Town
TerrainImprovementType <|-- Path
                            Path <|-- Road
                            Path <|-- Trail
@enduml
