@startuml
hide circle
' <|-- is "extention" and used for class inheritence
' *-- is composition (static aggregation), for when b is permanently "part of" a
' o-- is aggregation (dynamic aggregation)

class Map {
    -Hex[] hexes
	Hex getHex(int)

}

class Hex {
	-Hex[] neighbors
	Hex neighbor(Direction)
}

Map o-- "0..n" UnitStack
Map *-- "2046" Hex

Hex *-- Terrain
Hex *-- "0..1" Path
               Path <|-- Road
               Path <|-- Trail
Hex *-- "6" HexEdge
HexEdge *-- "0..1" Border
HexEdge *-- "0..1" Stream
HexEdge *-- "0..1" Wall
                   Wall <|-- SolidWall
                   Wall <|-- Gate
Terrain <|-- Clear
Terrain <|-- Forest
Terrain <|-- Woods
Terrain <|-- Broken
Terrain <|-- Rough
Terrain <|-- Glacier
Terrain <|-- Cultivated
Terrain <|-- Swamp
Terrain <|-- Karoo
Terrain <|-- Water
Terrain <|-- Mountain

'Hex Stuff:
'Tunnel, Vortex, Portal, Volcano,Capital
'
'Ford, Capital
'Hex Edge Terrain:
'Stream, Wall, Gate, 
@enduml
