@startuml

title <b>spell class diagrams</b>\nTao Zhang\nReviewed by Jay
hide circle
class character{
  +Name:    string
  +Magic PL: int
  +Magic Potential: int
  +Magic Color: string
  +Home Hex: int
  +Magic Profile: int
  +Magic Resistance: int
  +Current Location: int
  + ...
  + ...()
  +CastSpell()  : void
  +DieRoll_High_PL()
  + ...()
}

class spell{
  +Name:        string
  +index:       int
  +PowerLevel:  int
  +ManaCost:    int
  +Range:       int 
  +Limits:      ??
  +Effects:     string
  +Search_Spell_Book()
  +Search_target()
  +CastSpell()
}

class spell_book{
  +Spells_By_PL: string[]
  +Spells_By_Available_Mana: string[]
  +Look_up_by_PL()
  +Look_up_by_Avaiblable_Mana()
}

package spells{
  class spell1
  class spell2
}

class spell_target{
  +Name:        string
  +Current Location: int
  +Magic Resistance: int
}

character <|-right-- spell
spell <|-right- spell_book
spell <|-up- spell_target

spell_book <|-down-- spell1
spell_book <|-down-- spell2

@enduml